name: CI Workflow
on:
  pull_request:
    branches: [test/cache-busting]
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_GITHUB_S3_PUSHER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_GITHUB_S3_PUSHER_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - uses: dkershner6/aws-ssm-getparameters-action@v1
        with:
          parameterPairs: '/dev/deploy/crowdbible/env = ENV'

      - name: store env
        run: |
          cat << EOF > .env
          ${{ env.ENV }}
          CI=false
          NODE_OPTIONS=--max-old-space-size=4096
          EOF

      - name: Load env
        uses: xom9ikk/dotenv@v2
      
      - name: Configure Git
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Increase package.json version
        run: |
          echo "::set-output name=new_version::$(npm version patch)"
          npm version --no-git-tag-version ${{ steps.increase_version.outputs.new_version }}

      - name: Commit changes
        run: |
          git diff --quiet
          git commit -a -m "Bump version to ${{ steps.increase_version.outputs.new_version }}"
          
      # - name: npm ci --force
      #   run: npm ci --force

      # - name: npm run build
      #   run: npm run build