name: Pre-Test Workflow
on:
  pull_request:
    branches: [dev]
    types: [opened, synchronize, reopened]

jobs:
  docker-env-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: './.github/docker/docker-compose.yml'
          down-flags: '--volumes'
          services: |
            postgres
            cpg-server
            postgres-sso
            keycloak

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: store env
        run: |
          cat << EOF > .env
          CI=true
          NODE_OPTIONS=--max-old-space-size=4096
          EOF

      - name: Load env
        uses: xom9ikk/dotenv@v2

      - name: npm ci --force
        run: npm ci --force

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run unit test
        run: npm run test

      - name: Run Playwright tests
        run: |
          npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
